#!/usr/bin/env python3
"""Collect everything the morning brief needs into one file: kb/briefs/<date>.inputs.md.

  python scripts/brief_collect.py [--date 2026-09-15] [--kb kb] [--tracker tracker/actions.xlsx] [--engagements engagements]

Deterministic part of workflow #7. Reads today's calendar export, the tracker, today's triage/digests,
1-1 history for people you meet today, and every engagement's gate state; computes clashes, overdue
and due-soon items; writes the inputs file. Copilot's /morning-brief then turns it into the one-page brief.
"""
import argparse
import datetime as dt
import json
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kb_index import md_tables, read, dated_files, open_items  # noqa: E402
from kb_ingest import slug  # noqa: E402


def to_min(hhmm):
    m = re.match(r"^(\d{1,2}):(\d{2})$", hhmm.strip())
    return int(m.group(1)) * 60 + int(m.group(2)) if m else None


def calendar_for(kb, date):
    """Return (events, source_file, stale) for the date, from the newest calendar export that has an H3 for it."""
    files = dated_files(os.path.join(kb, "calendar"))
    for fdate, f in files:
        if fdate > date:
            continue
        text = read(os.path.join(kb, "calendar", f))
        sections = re.split(r"^###\s+", text, flags=re.M)
        for sec in sections[1:]:
            head, _, body = sec.partition("\n")
            if head.strip().startswith(date):
                events = []
                for header, rows in md_tables(body):
                    if "title" in [h.lower() for h in header]:
                        events.extend(rows)
                return events, f, fdate != date
    return [], None, True


def clashes(events):
    timed = []
    for e in events:
        s, t = to_min(e.get("start", "")), to_min(e.get("end", ""))
        if s is not None and t is not None:
            timed.append((s, t, e))
    out = []
    for i in range(len(timed)):
        for j in range(i + 1, len(timed)):
            a, b = timed[i], timed[j]
            if a[0] < b[1] and b[0] < a[1]:
                out.append((a[2], b[2]))
    return out


def tracker_rows(tracker):
    if not tracker or not os.path.exists(tracker):
        return None
    import xlsxlite
    _, rows = xlsxlite.read_rows(tracker)
    return [r for r in rows if not re.match(r"^(done|closed)", r.get("status", "").lower())]


def engagements_state(root):
    out = []
    if not os.path.isdir(root):
        return out
    for name in sorted(os.listdir(root)):
        sp = os.path.join(root, name, "state.json")
        if not os.path.exists(sp):
            continue
        try:
            st = json.load(open(sp, encoding="utf-8"))
        except Exception:
            continue
        gates = st.get("gates", {})
        kind = st.get("kind", "proposal")
        applicable = {"proposal": ["G1", "G2", "G3", "G4", "G5"], "deck": ["G1", "G3", "G4"], "meeting": ["G5"]}.get(kind, [])
        next_gate = next((g for g in applicable if not gates.get(g, {}).get("passed")), None)
        out.append((name, kind, next_gate, st.get("subject", "")))
    return out


def fmt_event(e):
    return "%s–%s %s (%s%s)" % (e.get("start", ""), e.get("end", ""), e.get("title", ""), e.get("kind", ""),
                                (", " + e["notes"]) if e.get("notes") else "")


def build(kb, date, tracker, engagements):
    today = dt.date.fromisoformat(date)
    out = ["<!-- GENERATED by scripts/brief_collect.py — inputs for /morning-brief, not the brief itself -->",
           "# Brief inputs — %s (%s)" % (date, today.strftime("%A")), ""]
    warnings = []

    # calendar
    events, src, stale = calendar_for(kb, date)
    out += ["## Calendar", ""]
    if not events:
        warnings.append("no calendar export covers %s — run the Daily Exporter in M365 Copilot and ingest it" % date)
        out.append("_no events known for %s_" % date)
    else:
        if stale:
            warnings.append("calendar for %s comes from an older export (%s); today's may have changed" % (date, src))
        for e in events:
            out.append("- " + fmt_event(e) + ((" — with: " + e["with"]) if e.get("with") else ""))
        cl = clashes(events)
        out += ["", "### Clashes", ""]
        out += ["- %s  ⟂  %s" % (fmt_event(a), fmt_event(b)) for a, b in cl] or ["_none_"]
    out.append("")

    # 1-1s today → people history
    ones = [e for e in events if e.get("kind", "").strip() == "1-1"]
    out += ["## 1-1s today", ""]
    if not ones:
        out.append("_none_")
    for e in ones:
        person = e.get("with", "").strip()
        pdir = os.path.join(kb, "people", slug(person))
        files = [(d, f) for d, f in dated_files(pdir) if f != "profile.md"] if os.path.isdir(pdir) else []
        if not files:
            out.append("- **%s** — no local 1-1 history (run the 1-1 Prep agent in M365 Copilot before the meeting)" % person)
            continue
        latest = read(os.path.join(pdir, files[0][1]))
        out.append("- **%s** — latest entry %s, %d open follow-up/action row(s): kb/people/%s/%s" % (
            person, files[0][0], open_items(latest), slug(person), files[0][1]))
        # pull the open follow-ups inline
        for header, rows in md_tables(latest):
            hl = [h.lower() for h in header]
            if "status" in hl and ("follow-up" in hl or "action" in hl):
                key = header[hl.index("status")]
                for r in rows:
                    if not re.match(r"^(done|closed|resolved|dropped)", r.get(key, "").lower()):
                        out.append("  - %s" % (r.get("follow-up") or r.get("action") or ""))
    out.append("")

    # tracker
    rows = tracker_rows(tracker)
    out += ["## Actions (tracker)", ""]
    if rows is None:
        warnings.append("no tracker at %s" % tracker)
        out.append("_no tracker_")
    else:
        soon = (today + dt.timedelta(days=7)).isoformat()
        overdue = [r for r in rows if r.get("due") and r["due"] < date and r.get("owner", "me") == "me"]
        due_today = [r for r in rows if r.get("due") == date and r.get("owner", "me") == "me"]
        due_soon = [r for r in rows if r.get("due") and date < r["due"] <= soon and r.get("owner", "me") == "me"]
        urgent = [r for r in rows if r.get("urgency", "").lower() == "high" and not r.get("due") and r.get("owner", "me") == "me"]
        delegated = [r for r in rows if r.get("owner", "me") not in ("me", "")]
        blocked = [r for r in rows if r.get("depends_on")]

        def block(title, items, show_due=True):
            out.append("### %s (%d)" % (title, len(items)))
            out.append("")
            for r in items[:15]:
                out.append("- %s%s  _[%s · %s%s]_" % (
                    r.get("action", ""), (" — due " + r["due"]) if show_due and r.get("due") else "",
                    r.get("source", ""), r.get("context", ""),
                    (" · " + r["owner"]) if r.get("owner") not in ("me", "") else ""))
            if len(items) > 15:
                out.append("- … %d more" % (len(items) - 15))
            if not items:
                out.append("_none_")
            out.append("")
        block("Overdue (mine)", overdue)
        block("Due today (mine)", due_today)
        block("Due within 7 days (mine)", due_soon)
        block("Urgent, no date (mine)", urgent, show_due=False)
        block("Waiting on others (delegated)", delegated)
        block("Blocked by something", blocked)
        mine_open = len([r for r in rows if r.get("owner", "me") in ("me", "")])
        out.append("Open total: %d (mine %d, delegated %d)" % (len(rows), mine_open, len(delegated)))
        out.append("")

    # email triage & topic digests
    out += ["## Today's inputs status", ""]
    has_email = os.path.exists(os.path.join(kb, "email", "%s.md" % date))
    has_triage = os.path.exists(os.path.join(kb, "triage", "%s.md" % date))
    if has_triage:
        out.append("- email triage for %s: done → kb/triage/%s.md" % (date, date))
    elif has_email:
        out.append("- email export for %s present, NOT triaged yet → run `/triage-inbox date=%s`" % (date, date))
    else:
        out.append("- no email export for %s" % date)
    tdir = os.path.join(kb, "topics")
    if os.path.isdir(tdir):
        for t in sorted(os.listdir(tdir)):
            if not os.path.isdir(os.path.join(tdir, t)):
                continue
            d = os.path.join(tdir, t, "digests", "%s.md" % date)
            l = os.path.join(tdir, t, "links", "%s.md" % date)
            if os.path.exists(d):
                digest = read(d)
                flagged = re.search(r"^## Flagged.*?$(.*?)^## ", digest, flags=re.M | re.S)
                n = len(re.findall(r"^\s*(?:\d+\.|-)\s", flagged.group(1), flags=re.M)) if flagged else 0
                out.append("- topic **%s**: digest ready (%d flagged) → kb/topics/%s/digests/%s.md" % (t, n, t, date))
            elif os.path.exists(l):
                out.append("- topic **%s**: links present, no digest → run `/triage-topic topic=%s date=%s`" % (t, t, date))
    out.append("")

    # engagements
    out += ["## Engagements (D2P) — where each one stands", ""]
    eng = engagements_state(engagements)
    if not eng:
        out.append("_none_")
    for name, kind, gate, subject in eng:
        if gate is None:
            continue  # finished
        out.append("- %s (%s%s) — waiting on you at **%s**: `python scripts/status.py engagements/%s`" % (
            name, kind, (": " + subject) if subject else "", gate, name))
    out.append("")

    # yesterday's brief carry-over
    yday = (today - dt.timedelta(days=1)).isoformat()
    yb = os.path.join(kb, "briefs", "%s.md" % yday)
    if os.path.exists(yb):
        text = read(yb)
        m = re.search(r"^## (?:Top 3|Focus).*?$(.*?)(?:^## |\Z)", text, flags=re.M | re.S)
        if m:
            out += ["## Yesterday's focus (from %s brief)" % yday, "", m.group(1).strip(), ""]

    if warnings:
        out += ["## Warnings", ""] + ["- " + w for w in warnings] + [""]
    os.makedirs(os.path.join(kb, "briefs"), exist_ok=True)
    target = os.path.join(kb, "briefs", "%s.inputs.md" % date)
    with open(target, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return target, warnings


def _selftest():
    import xlsxlite
    from tracker_init import HEADER
    with tempfile.TemporaryDirectory() as d:
        kb = os.path.join(d, "kb")
        os.makedirs(os.path.join(kb, "calendar"))
        os.makedirs(os.path.join(kb, "people", "maria-k"))
        os.makedirs(os.path.join(kb, "email"))
        os.makedirs(os.path.join(kb, "topics", "ai", "links"))
        with open(os.path.join(kb, "calendar", "2026-09-15.md"), "w") as f:
            f.write("---\nhandoff: calendar\ndate: 2026-09-15\n---\n## Calendar\n### 2026-09-15\n"
                    "| start | end | title | with | kind | link | notes |\n|---|---|---|---|---|---|---|\n"
                    "| 09:00 | 09:30 | Weekly 1-1 | Maria K | 1-1 | | |\n| 09:15 | 10:00 | Sync | Jan D | meeting | | |\n"
                    "| 14:00 | 15:00 | Focus | — | focus | | |\n### 2026-09-16\n| start | end | title | with | kind | link | notes |\n|---|---|---|---|---|---|---|\n| 10:00 | 11:00 | X | Y | meeting | | |\n")
        with open(os.path.join(kb, "people", "maria-k", "2026-09-01.md"), "w") as f:
            f.write("## Open follow-ups\n| raised on | follow-up | status |\n|---|---|---|\n| 2026-08-18 | ask about training budget | open |\n")
        open(os.path.join(kb, "email", "2026-09-15.md"), "w").close()
        open(os.path.join(kb, "topics", "ai", "links", "2026-09-15.md"), "w").close()
        tracker = os.path.join(d, "actions.xlsx")
        xlsxlite.create(tracker, HEADER)
        xlsxlite.append_rows(tracker, [
            ["1", "2026-09-01", "email-triage", "c", "me", "Overdue thing", "2026-09-10", "", "", "open", "", ""],
            ["2", "2026-09-01", "d2p", "c", "delegate:jan-d", "Delegated thing", "", "", "", "open", "", ""],
            ["3", "2026-09-01", "d2p", "c", "me", "Done thing", "2026-09-10", "", "", "done", "", ""],
            ["4", "2026-09-01", "d2p", "c", "me", "Today thing", "2026-09-15", "high", "S", "open", "", ""],
        ])
        eng = os.path.join(d, "engagements", "2026-09-acme")
        os.makedirs(eng)
        json.dump({"kind": "proposal", "gates": {"G1": {"passed": True}}}, open(os.path.join(eng, "state.json"), "w"))
        target, warnings = build(kb, "2026-09-15", tracker, os.path.join(d, "engagements"))
        text = read(target)
        assert "09:00–09:30 Weekly 1-1 (1-1)  ⟂  09:15–10:00 Sync (meeting)" in text, text
        assert "ask about training budget" in text
        assert "### Overdue (mine) (1)" in text and "### Due today (mine) (1)" in text and "Delegated thing" in text
        assert "Done thing" not in text
        assert "NOT triaged yet" in text and "no digest" in text
        assert "waiting on you at **G2**" in text
        assert "2026-09-16" not in text.split("## 1-1s")[0].split("## Calendar")[1]
        assert not warnings, warnings
        t2, w2 = build(kb, "2026-09-17", tracker, os.path.join(d, "engagements"))
        assert any("no calendar export covers" in w for w in w2), w2
    print("brief_collect selftest OK")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--date", default=dt.date.today().isoformat())
    ap.add_argument("--kb", default="kb")
    ap.add_argument("--tracker", default=os.path.join("tracker", "actions.xlsx"))
    ap.add_argument("--engagements", default="engagements")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        _selftest()
    else:
        target, warnings = build(a.kb, a.date, a.tracker, a.engagements)
        print("wrote %s" % target)
        for w in warnings:
            print("warning: " + w)
        print("next: in Copilot Chat, @librarian /morning-brief date=%s" % a.date)
