#!/usr/bin/env python3
"""Generate docs/menu.md, the routing table the /start guide reads, from city/city.json (or flows.json).

The source is the single place for "what can I do here": its journeys and the buildings' steps with the exact
commands. In semiAgency that is city/city.json (the map is generated from it too, so guide and map cannot
disagree); a workspace without a map uses flows.json with the same "journeys"/"buildings" shape. An optional
"elsewhere" list adds other workspaces' menus (by title) with the command that switches to them.
This file is identical in every workspace that uses it.

Usage:
  python3 scripts/build_menu.py            regenerate docs/menu.md
  python3 scripts/build_menu.py --check    exit 1 if docs/menu.md is stale or a prompt is not reachable from it
  python3 scripts/build_menu.py --selftest
"""
import argparse
import json
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join("docs", "menu.md")
SOURCES = [os.path.join("city", "city.json"), "flows.json"]
WHERE = {"vscode": "VS Code (this workspace)", "m365": "Microsoft 365 (Outlook, Teams, Copilot Chat)",
         "everyone": "VS Code or Microsoft 365", "here": "here (this workspace)"}
GUIDE_PROMPTS = {"start"}  # the guide itself is not a destination


def one_line(s):
    return re.sub(r"\s+", " ", (s or "").strip())


def short(s, limit=240):
    """First sentences of a step with no command, up to about `limit` characters."""
    s = one_line(s)
    if len(s) <= limit:
        return s
    cut = max(s.rfind(". ", 0, limit), s.rfind("; ", 0, limit))
    return (s[:cut + 1] if cut > 60 else s[:limit].rsplit(" ", 1)[0]) + " …"


def source_path(root):
    for rel in SOURCES:
        if os.path.exists(os.path.join(root, rel)):
            return rel
    raise SystemExit("no menu source: expected one of " + ", ".join(SOURCES))


def elsewhere_titles(root, menu_rel):
    p = os.path.normpath(os.path.join(root, menu_rel))
    if not os.path.exists(p):
        return None
    return [re.sub(r"^##\s+\d+\.\s*", "", l).strip() for l in open(p, encoding="utf-8") if re.match(r"^##\s+\d+\.", l)]


def render(city, src="city/city.json", root=None):
    b = {x["id"]: x for x in city.get("buildings", [])}
    out = ["# Menu — what you can do here",
           "",
           "<!-- GENERATED by scripts/build_menu.py from %s. Edit that file, then re-run the script. -->" % src,
           "The `/start` guide reads this file. Each numbered item is one thing you can want; its steps are in order,",
           "and each step names where it happens and the exact command to type.",
           ""]
    for n, j in enumerate(city.get("journeys", []), 1):
        out.append("## %d. %s" % (n, one_line(j["q"])))
        out.append("- id: `%s` · where: %s · time: %s" % (j["id"], WHERE.get(j.get("audience"), j.get("audience", "")),
                                                          one_line(j.get("time"))))
        out.append("- when: " + one_line(j.get("when")))
        out.append("- bring: " + one_line(j.get("bring")))
        out.append("- you get: " + one_line(j.get("get")))
        out.append("- steps:")
        for i, stop in enumerate(j.get("stops", []), 1):
            bd = b.get(stop["building"], {})
            out.append("  %d. **%s** — %s" % (i, bd.get("name", stop["building"]), one_line(stop.get("say"))))
            for st in bd.get("steps", []):
                if st.get("copy"):
                    out.append("     - %s `%s`" % (one_line(st.get("say")).rstrip(":") + ":", st["copy"]))
                elif st.get("say"):
                    out.append("     - " + short(st["say"]))
            for d in bd.get("docs", []):
                out.append("     - read: `%s` (%s)" % (d["file"], one_line(d.get("title"))))
        out.append("")
    for e in city.get("elsewhere", []):
        titles = elsewhere_titles(root or ROOT, e["menu"])
        out.append("## Elsewhere: %s" % e["name"])
        out.append("- switch: %s" % e["switch"])
        if titles is None:
            out.append("- (its menu `%s` was not found on this machine)" % e["menu"])
        for t in titles or []:
            out.append("- " + t)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def prompt_names(root):
    d = os.path.join(root, ".github", "prompts")
    if not os.path.isdir(d):
        return []
    return sorted(f[:-len(".prompt.md")] for f in os.listdir(d) if f.endswith(".prompt.md"))


def unreachable(root, menu):
    """Prompts that exist but that the guide could never send you to."""
    return [p for p in prompt_names(root)
            if p not in GUIDE_PROMPTS and not re.search(r"[`\s]/%s(?![\w-])" % re.escape(p), menu)]


def build(root, check=False):
    src = source_path(root)
    with open(os.path.join(root, src), encoding="utf-8") as fh:
        menu = render(json.load(fh), src.replace(os.sep, "/"), root)
    path = os.path.join(root, OUT)
    cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    stale = cur != menu
    if stale and not check:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(menu)
    return stale, unreachable(root, menu), menu


def _selftest():
    tmp = tempfile.mkdtemp()
    try:
        os.makedirs(os.path.join(tmp, "city"))
        os.makedirs(os.path.join(tmp, ".github", "prompts"))
        for p in ("meeting-notes", "start", "orphan"):
            open(os.path.join(tmp, ".github/prompts/%s.prompt.md" % p), "w").write("---\n---\nx\n")
        city = {"buildings": [{"id": "notary", "name": "The Notary",
                               "steps": [{"say": "In Copilot Chat:", "copy": "/meeting-notes"}, {"say": "no copy"}],
                               "docs": [{"title": "Runbook", "file": "docs/runbooks/meeting.md"}]}],
                "journeys": [{"id": "meeting", "audience": "vscode", "q": "Record a meeting", "when": "a\n meeting",
                              "bring": "transcript", "get": "notes", "time": "10 min",
                              "stops": [{"building": "notary", "say": "Write it up."}]}]}
        json.dump(city, open(os.path.join(tmp, "city/city.json"), "w"))
        stale, unr, menu = build(tmp)
        assert stale and unr == ["orphan"], unr
        assert "## 1. Record a meeting" in menu and "when: a meeting" in menu
        assert "**The Notary** — Write it up." in menu and "In Copilot Chat: `/meeting-notes`" in menu
        assert "     - no copy" in menu and "read: `docs/runbooks/meeting.md`" in menu
        assert short("A" * 70 + ". " + "b " * 200).endswith(". …")
        stale, _, _ = build(tmp, check=True)
        assert not stale
        # a workspace without a map: flows.json, plus another workspace's menu listed by title
        other = os.path.join(tmp, "other")
        os.makedirs(os.path.join(other, "docs"))
        open(os.path.join(other, "docs", "menu.md"), "w").write("# Menu\n## 1. Record a meeting\n## 2. Make a deck\n")
        os.remove(os.path.join(tmp, "city", "city.json"))
        city["elsewhere"] = [{"name": "Work", "menu": "other/docs/menu.md", "switch": "`jarvis work`"},
                             {"name": "Gone", "menu": "nope/menu.md", "switch": "x"}]
        json.dump(city, open(os.path.join(tmp, "flows.json"), "w"))
        _, _, menu = build(tmp)
        assert "from flows.json" in menu and "## Elsewhere: Work\n- switch: `jarvis work`\n- Record a meeting\n- Make a deck" in menu, menu
        assert "was not found" in menu
    finally:
        shutil.rmtree(tmp)
    print("build_menu selftest OK")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        _selftest()
        return
    stale, unr, menu = build(ROOT, check=a.check)
    for p in unr:
        print("NOT ON THE MENU  /%s — add it to a building's steps (\"copy\": \"/%s\") on a journey in city/city.json" % (p, p))
    if a.check:
        if stale:
            print("STALE  %s — in the terminal: python3 scripts/build_menu.py" % OUT)
        if stale or unr:
            sys.exit(1)
        print("%s is up to date; every prompt is reachable from it." % OUT)
        return
    print("Wrote %s (%d lines)." % (OUT, menu.count("\n")))
    if unr:
        sys.exit(1)


if __name__ == "__main__":
    main()
