#!/usr/bin/env python3
"""Rebuild the generated views of the knowledge base:
  kb/index.md                     what is in the KB, newest first
  kb/topics/<topic>/links.md      every link ever collected for the topic, one table, deduplicated by URL

  python scripts/kb_index.py [--kb kb] [--tracker tracker/actions.xlsx]
Safe to run any time; only touches the two generated files.
"""
import argparse
import datetime as dt
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")


def dated_files(folder, pattern=r".*\.md$"):
    if not os.path.isdir(folder):
        return []
    out = []
    for f in os.listdir(folder):
        if re.match(pattern, f) and not f.startswith(".") and f != "links.md":
            m = DATE_RE.search(f)
            out.append((m.group(1) if m else "0000-00-00", f))
    return sorted(out, reverse=True)


def md_tables(text):
    """Yield (header_list, rows) for every pipe table in a markdown text."""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if lines[i].strip().startswith("|") and i + 1 < len(lines) and re.match(r"^\s*\|?\s*:?-{2,}", lines[i + 1]):
            header = [c.strip() for c in lines[i].strip().strip("|").split("|")]
            rows = []
            i += 2
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                cells += [""] * (len(header) - len(cells))
                rows.append(dict(zip(header, cells)))
                i += 1
            yield header, rows
        else:
            i += 1


def read(path):
    with open(path, encoding="utf-8-sig") as f:
        return f.read()


def open_items(text):
    """Count table rows whose 'status' column is not done/closed/resolved/dropped."""
    n = 0
    for header, rows in md_tables(text):
        if "status" in [h.lower() for h in header]:
            key = [h for h in header if h.lower() == "status"][0]
            for r in rows:
                if not re.match(r"^(done|closed|resolved|dropped|cancelled|canceled)", r.get(key, "").lower()):
                    n += 1
    return n


def build_links(topic_dir):
    links_dir = os.path.join(topic_dir, "links")
    seen, rows = set(), []
    for date, f in dated_files(links_dir):
        for header, trs in md_tables(read(os.path.join(links_dir, f))):
            if "url" not in [h.lower() for h in header]:
                continue
            for r in trs:
                url = r.get("url", "").strip()
                if not url or url in seen:
                    continue
                seen.add(url)
                rows.append((date, r.get("title", ""), url, r.get("one-line", "")))
    out = ["<!-- GENERATED by scripts/kb_index.py — do not edit; edit links/<date>.md instead -->",
           "# All links — %s (%d unique)" % (os.path.basename(topic_dir), len(rows)), "",
           "| date | title | url | one-line |", "|---|---|---|---|"]
    for date, title, url, one in rows:
        out.append("| %s | %s | %s | %s |" % (date, title, url, one))
    with open(os.path.join(topic_dir, "links.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return len(rows)


def tracker_summary(tracker):
    if not tracker or not os.path.exists(tracker):
        return None
    try:
        import xlsxlite
        _, rows = xlsxlite.read_rows(tracker)
    except Exception as e:
        return "tracker unreadable: %s" % e
    open_rows = [r for r in rows if not re.match(r"^(done|closed)", r.get("status", "").lower())]
    by_source, by_owner, overdue = {}, {}, 0
    today = dt.date.today().isoformat()
    for r in open_rows:
        by_source[r.get("source", "")] = by_source.get(r.get("source", ""), 0) + 1
        by_owner[r.get("owner", "")] = by_owner.get(r.get("owner", ""), 0) + 1
        if r.get("due") and r["due"] < today:
            overdue += 1
    return "%d open (%d overdue) — by source: %s — by owner: %s" % (
        len(open_rows), overdue,
        ", ".join("%s %d" % kv for kv in sorted(by_source.items())) or "–",
        ", ".join("%s %d" % kv for kv in sorted(by_owner.items())) or "–")


def build(kb, tracker=None):
    out = ["<!-- GENERATED by scripts/kb_index.py — do not edit -->",
           "# Knowledge base index — %s" % dt.datetime.now().strftime("%Y-%m-%d %H:%M"), ""]
    ts = tracker_summary(tracker)
    if ts:
        out += ["## Tracker", "", ts, ""]
    # topics
    tdir = os.path.join(kb, "topics")
    if os.path.isdir(tdir):
        topics = sorted(t for t in os.listdir(tdir) if os.path.isdir(os.path.join(tdir, t)))
        if topics:
            out += ["## Topics", ""]
            for t in topics:
                td = os.path.join(tdir, t)
                n_links = build_links(td)
                prof = os.path.exists(os.path.join(td, "profile.md"))
                digests = dated_files(os.path.join(td, "digests"))
                link_days = dated_files(os.path.join(td, "links"))
                out.append("- **%s** — profile: %s · %d link(s) over %d day(s) ([all](topics/%s/links.md)) · latest digest: %s" % (
                    t, "yes" if prof else "MISSING (run /interview-topic topic=%s)" % t, n_links, len(link_days), t,
                    ("[%s](topics/%s/digests/%s)" % (digests[0][1], t, digests[0][1])) if digests else "none"))
                if link_days and (not digests or digests[0][0] < link_days[0][0]):
                    out.append("  - links for %s have no digest yet → /triage-topic topic=%s date=%s" % (link_days[0][0], t, link_days[0][0]))
            out.append("")
    # meetings, notes
    for name, folder in [("Meetings waiting for an engagement", "meetings"), ("Notes", "notes")]:
        files = dated_files(os.path.join(kb, folder))
        if files:
            out += ["## %s (%d)" % (name, len(files)), ""] + ["- [%s](%s/%s)" % (f, folder, f) for d, f in files[:15]] + [""]
    inbox = [f for f in os.listdir(os.path.join(kb, "inbox")) if not f.startswith(".")] if os.path.isdir(os.path.join(kb, "inbox")) else []
    if inbox:
        out += ["## Inbox — NOT YET INGESTED", ""] + ["- %s" % f for f in inbox] + ["", "run `python scripts/kb_ingest.py`", ""]
    with open(os.path.join(kb, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    return os.path.join(kb, "index.md")


def _selftest():
    with tempfile.TemporaryDirectory() as d:
        kb = os.path.join(d, "kb")
        os.makedirs(os.path.join(kb, "topics/ai/links"))
        os.makedirs(os.path.join(kb, "inbox"))
        with open(os.path.join(kb, "topics/ai/links/2026-09-14.md"), "w") as f:
            f.write("| url | title | one-line |\n|---|---|---|\n| https://a | A | one |\n| https://b | B | two |\n")
        with open(os.path.join(kb, "topics/ai/links/2026-09-15.md"), "w") as f:
            f.write("| url | title | one-line |\n|---|---|---|\n| https://b | B again | dup |\n| https://c | C | three |\n")
        p = build(kb)
        idx = read(p)
        assert "3 link(s) over 2 day(s)" in idx, idx
        assert "no digest yet" in idx
        links = read(os.path.join(kb, "topics/ai/links.md"))
        assert links.count("https://b") == 1 and "| 2026-09-15 | C |" in links, links
    print("kb_index selftest OK")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--kb", default="kb")
    ap.add_argument("--tracker", default=os.path.join("tracker", "actions.xlsx"))
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        _selftest()
    else:
        print("wrote %s" % build(a.kb, a.tracker))
